// <auto-generated />
using System;
using ITI_GProject.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITI_GProject.Migrations
{
    [DbContext(typeof(MarketPlace))]
    partial class MarketPlaceModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITI_GProject.Models.Client", b =>
                {
                    b.Property<string>("Clientid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Clientid");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ITI_GProject.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Clientid")
                        .HasColumnType("int");

                    b.Property<string>("Clientid1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Clientid1");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ITI_GProject.Models.Product", b =>
                {
                    b.Property<int>("Productid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Productid"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Proddescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prodname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sellerid")
                        .HasColumnType("int");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Productid");

                    b.HasIndex("OrderId");

                    b.HasIndex("Sellerid");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ITI_GProject.Models.Seller", b =>
                {
                    b.Property<int>("Sellerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sellerid"));

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sellerid");

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("ITI_GProject.Models.Order", b =>
                {
                    b.HasOne("ITI_GProject.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("Clientid1");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ITI_GProject.Models.Product", b =>
                {
                    b.HasOne("ITI_GProject.Models.Order", null)
                        .WithMany("Products")
                        .HasForeignKey("OrderId");

                    b.HasOne("ITI_GProject.Models.Seller", "Seller")
                        .WithMany("SellerProducts")
                        .HasForeignKey("Sellerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("ITI_GProject.Models.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ITI_GProject.Models.Order", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ITI_GProject.Models.Seller", b =>
                {
                    b.Navigation("SellerProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
